---
title: "Modeling"
output: html_notebook
---
```{r}
rm(list=ls())
require(ggplot2)
#install.packages("pscl")
#install.packages(glmmTMB)
#install.packages("DescTools")
require(DescTools)
require(glmmTMB)
require(pscl)
require(boot)
library(data.table)
library(tidyr)
library(dplyr)
library(stringr)
library(here)
library(phyloseq)
library(vegan)
library(refund)
library(reshape2)
library(kableExtra)
library(lme4)
library(MASS)
library(forcats)
library(GGally)
library(lmerTest)
library(gridExtra)
library(ggfortify)
library(performance)
library(plotly)
library(ggrepel)
library(factoextra)
library(lme4)
library(NBZIMM)
#remotes::install_github("palday/coefplot2",
#           subdir = "pkg")
library(coefplot2)
library(ggpubr)

#library(HMP2Data) #install the library from github
```


```{r}
#path to protected dbGap data location

local_path <- "~/Documents/MOMS-PI"# change me
#local_path <- "~/MOMS-PI"# change me

path2 <- file.path(local_path,"71694", "PhenoGenotypeFiles", "RootStudyConsentSet_phs001523.MOMS_PI.v1.p1.c1.DS-PREG-COM-IRB-PUB-MDS", "PhenotypeFiles") 

otu <- read.csv(file = file.path(path2, "MergedFiles", "OTU_table.csv"))
rownames(otu) <- otu$X
otu$X <- NULL 
t_otu <- as.data.frame(t(otu))
meta <- read.csv(file = file.path(path2, "MergedFiles", "Meta_data.csv"))
#physical activity variable
phys <- meta[,98:100]
meta$phys <- ifelse(meta$physical_activity_vigorous == "0_times" | is.na(meta$physical_activity_vigorous), "None", "Vigorous")
meta$phys[which(meta$phys == "None" & meta$physical_activity_moderate != "0_times" & !is.na(meta$physical_activity_moderate))] <- "Moderate"
meta$phys[which(meta$phys == "None" & meta$physical_activity_light != "0_times" & !is.na(meta$physical_activity_light))] <- "Light"
meta$phys <- as.factor(meta$phys)

#filter to just two races
meta <- meta %>%
  filter(race == "african_american" | race == "caucasian")
meta$race <- factor(meta$race)
rownames(meta) <- meta$X
meta$X <- NULL
t_otu <- t_otu[rownames(meta),]
```

```{r EditMeta}
meta <- meta %>%
  mutate(antibiotics_current = replace_na(antibiotics_current, "No"))

meta <- meta %>%
  mutate(infertility_treatment = replace_na(infertility_treatment, "No")) %>%
  mutate(infertility_treatment = recode(infertility_treatment, Not_sure = "No", .default = levels(meta$infertility_treatment)))

meta <- meta %>%
  mutate(vdischarge = replace_na(vdischarge, "No")) %>%
  mutate(vdischarge = recode(vdischarge, Not_Sure = "No", .default = levels(meta$vdischarge)))

meta <- meta %>%
  mutate(vodor = replace_na(vodor, "No")) %>%
  mutate(vodor = recode(vodor, Not_Sure = "No", .default = levels(meta$vodor)))

meta <- meta %>%
  mutate(vitching = replace_na(vitching, "No"))

meta <- meta %>%
  mutate(douche = replace_na(douche, "More_than_1_year_ago_or_never"))

meta <- meta %>%
  mutate(bv_history = replace_na(bv_history, "No")) %>%
  mutate(bv_history = recode(bv_history, Not_Sure = "No", .default = levels(meta$bv_history)))

meta <- meta %>%
  mutate(vaginitis_history = replace_na(vaginitis_history, "No"))

meta <- meta %>%
  mutate(current_medications = replace_na(current_medications, "No")) %>%
  mutate(current_medications = recode(current_medications, No_I_am_not_taking_any_new_medications = "No", .default = levels(meta$current_medications)))

meta <- meta %>%
  mutate(smoker_current = replace_na(smoker_current, "No"))

meta <- meta %>%
  mutate(alcohol_frequency_year = replace_na(alcohol_frequency_year, "0_times"))

meta <- meta %>%
  mutate(diabetes = replace_na(diabetes, "No")) %>%
  mutate(diabetes = recode(diabetes, Not_sure = "No", .default = levels(meta$diabetes)))

meta <- meta %>%
  mutate(no_false_labor = replace_na(no_false_labor, "Yes")) %>%
  mutate(no_false_labor = recode(no_false_labor, No_I_have_not_experienced_false_labor = "Yes", .default = levels(meta$no_false_labor)))

meta <- meta %>%
  mutate(no_high_bp = replace_na(no_high_bp, "Yes"))

meta <- meta %>%
  mutate(no_vbleeding = replace_na(no_vbleeding, "Yes"))

meta <- meta %>%
  mutate(progesterone = replace_na(progesterone, "No")) %>%
  mutate(progesterone = recode(progesterone, Not_Sure = "No", .default = levels(meta$progesterone)))

levels(meta$age)[1] <- NA
```


```{r }
#Create combined table
full_set <- cbind(t_otu, meta)
full_set$alpha_div <- diversity(full_set[,1:length(names(t_otu))], index="shannon")
full_set$num_reads <- rowSums(t_otu)

#Add vagitype
mypropdata <- full_set[,colnames(t_otu)]
mytypes <- apply(mypropdata,1,which.max)
maxprop <- as.numeric(mypropdata[matrix(c(1:nrow(mypropdata),mytypes), ncol=2)])
mytypes <- colnames(mypropdata)[mytypes]
mytypes[maxprop < 0.3] <- "No Type"
mytypes <- as.factor(mytypes)
full_set <- full_set %>%
  mutate(vagitype=mytypes)
high_vagitype <- sort(table(full_set$vagitype), decreasing=T)[1:5]
high_vagitype
#Add proportions
full_set$p_Iners <- full_set$Lactobacillus_iners/full_set$num_reads
full_set$p_Crisp <- full_set$Lactobacillus_crispatus_cluster/full_set$num_reads
full_set$p_Gard <- full_set$Gardnerella_vaginalis/full_set$num_reads
full_set$Gass <- full_set$Lactobacillus_gasseri_cluster/full_set$num_reads
full_set$p_BVAB <- full_set$Lachnospiraceae_BVAB1/full_set$num_reads

```





```{r}
get_mode = function(x, multimodal.na="TRUE"){
  modes <- Mode(x)
  if (multimodal.na=="FALSE" | length(modes)==1) {
    return(modes[1]) 
  } else {
    return(modes[length(modes)+1])
  }
}

#582 subjects
#aggregate at patient level
demog <- aggregate(visit_number ~ SUBJECT_ID, data = meta%>%data.frame, FUN = min)
demog <- merge(demog,meta%>%data.frame, by = c("SUBJECT_ID", "visit_number") )
  
#number visits per subject 
df <- aggregate(visit_number ~ SUBJECT_ID, data = meta%>%data.frame, FUN = length)
colnames(df)[which(colnames(df) == "visit_number")] <- "number of visits"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average income per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(income = get_mode(income, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "income")] <- "average income"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average education per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(education = get_mode(education, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "education")] <- "average education"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average age per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(age = get_mode(age, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "age")] <- "average age"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average prenatal care start per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(prenatal_care_start = get_mode(prenatal_care_start, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "prenatal_care_start")] <- "average p_care_start"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average infertility treatment per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(infertility_treatment = get_mode(infertility_treatment, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "infertility_treatment")] <- "average inf_trt"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average v_discharge per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(vdischarge = get_mode(vdischarge, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "vdischarge")] <- "average v_discharge"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average v_odor per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(vodor = get_mode(vodor, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "vodor")] <- "average v_odor"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average v_itching per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(vitching = get_mode(vitching, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "vitching")] <- "average v_itching"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average douche per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(douche = get_mode(douche, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "douche")] <- "average douche"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average bv_history per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(bv_history = get_mode(bv_history, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "bv_history")] <- "average bv_history"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average vaginitis_history per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(vaginitis_history = get_mode(vaginitis_history, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "vaginitis_history")] <- "average vaginitis_history"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average current_medications per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(current_medications = get_mode(current_medications, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "current_medications")] <- "average current_medications"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average smoker_current per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(smoker_current = get_mode(smoker_current, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "smoker_current")] <- "average smoker_current"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average alcohol_frequency per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(alcohol_frequency_year = get_mode(alcohol_frequency_year, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "alcohol_frequency_year")] <- "average alcohol_frequency"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average diabetes per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(diabetes = get_mode(diabetes, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "diabetes")] <- "average diabetes"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average false_labor per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(no_false_labor = get_mode(no_false_labor, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "no_false_labor")] <- "average no_false_labor"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average high_bp per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(no_high_bp = get_mode(no_high_bp, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "no_high_bp")] <- "average no_high_bp"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average v_bleeding per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(no_vbleeding = get_mode(no_vbleeding, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "no_vbleeding")] <- "average no_vbleeding"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average progesterone per subject 
df <- meta %>% group_by(SUBJECT_ID) %>% summarise(progesterone = get_mode(progesterone, multimodal.na = "FALSE"))
colnames(df)[which(colnames(df) == "progesterone")] <- "average progesterone"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#average vaginal_ph across visits
#Some patients have na so goes to 568
df <- aggregate(vaginal_pH ~ SUBJECT_ID, data = meta%>%data.frame, FUN = mean)
colnames(df)[which(colnames(df) == "vaginal_pH")] <- "mean_vaginal_ph"
demog <- merge(demog,df, by = c("SUBJECT_ID") )
#alpha diversity
df <- aggregate(alpha_div ~ SUBJECT_ID, data = full_set%>%data.frame, FUN = mean)
colnames(df)[which(colnames(df) == "alpha_div")] <- "mean_alpha_div"
demog <- merge(demog,df, by = c("SUBJECT_ID") )

#reported_ga is only for minimum recorded visit for each individual
Varnames <- c("mean_vaginal_ph", "number of visits", "reported_ga", "mean_alpha_div", "average income", 
              "average education", "average age", "average p_care_start", "average inf_trt", 
              "average  v_discharge", "average v_odor", "average v_itching", "average douche", 
              "average bv_history", "average vaginitis_history", "average current_medications",
              "average smoker_current", "average alcohol_frequency", "average diabetes", 
              "average no_false_labor", "average no_high_bp", "average no_vbleeding", "average progesterone")
#racial breakdown, break down visits and other demographics
stratified1 = tableone::CreateTableOne(
  vars = Varnames[1:4],
  data = summarytools::unlabel(demog), strata = "race", includeNA = TRUE)
stratified2 = tableone::CreateTableOne(
  vars = Varnames[5:7],
  data = summarytools::unlabel(demog), strata = "race", includeNA = TRUE)
stratified3 = tableone::CreateTableOne(
  vars = Varnames[8:15],
  data = summarytools::unlabel(demog), strata = "race", includeNA = TRUE)
stratified4 = tableone::CreateTableOne(
  vars = Varnames[16:19],
  data = summarytools::unlabel(demog), strata = "race", includeNA = TRUE)
stratified5 = tableone::CreateTableOne(
  vars = Varnames[20:23],
  data = summarytools::unlabel(demog), strata = "race", includeNA = TRUE)

```

```{r }
#stratified1 <- print(stratified1, printToggle = FALSE, showAllLevels = FALSE)
#stratified1 = stratified1[,!(colnames(stratified1) %in% "test")]%>%
#  knitr::kable(format="latex")%>% 
#  kable_styling("striped", full_width = F, font_size = 9)
stratified1
#fix the part where every race is shown, probably due to meta being called
```

```{r }
#stratified1 <- print(stratified1, printToggle = FALSE, showAllLevels = FALSE)
#stratified1 = stratified1[,!(colnames(stratified1) %in% "test")]%>%
#  knitr::kable(format="latex")%>% 
#  kable_styling("striped", full_width = F, font_size = 9)
stratified2
#fix the part where every race is shown, probably due to meta being called
```

```{r }
#stratified1 <- print(stratified1, printToggle = FALSE, showAllLevels = FALSE)
#stratified1 = stratified1[,!(colnames(stratified1) %in% "test")]%>%
#  knitr::kable(format="latex")%>% 
#  kable_styling("striped", full_width = F, font_size = 9)
stratified3
#fix the part where every race is shown, probably due to meta being called
```

```{r }
#stratified1 <- print(stratified1, printToggle = FALSE, showAllLevels = FALSE)
#stratified1 = stratified1[,!(colnames(stratified1) %in% "test")]%>%
#  knitr::kable(format="latex")%>% 
#  kable_styling("striped", full_width = F, font_size = 9)
stratified4
#fix the part where every race is shown, probably due to meta being called
```

```{r }
#stratified1 <- print(stratified1, printToggle = FALSE, showAllLevels = FALSE)
#stratified1 = stratified1[,!(colnames(stratified1) %in% "test")]%>%
#  knitr::kable(format="latex")%>% 
#  kable_styling("striped", full_width = F, font_size = 9)
stratified5
#fix the part where every race is shown, probably due to meta being called
```

```{r}
#Find out individuals who have a different vagitype across visits
uniq_vagitype <- full_set %>%
  group_by(SUBJECT_ID) %>%
  summarize(n_unique = n_distinct(vagitype))
more_vagitype <- uniq_vagitype %>%
  filter(n_unique > 1)
full_set %>%
  filter(SUBJECT_ID %in% more_vagitype$SUBJECT_ID) %>%
  group_by(SUBJECT_ID) %>%
  distinct(vagitype)

#Look at proportional changes over time, look at differences betweeen those that did change and those that did not
#Look at how they change, if they change similarly
```



```{r}

count_table <- aggregate(list(full_set$Lactobacillus_iners, full_set$p_Iners,full_set$Lactobacillus_crispatus_cluster, full_set$p_Crisp, full_set$Gardnerella_vaginalis, full_set$p_Gard, full_set$Lactobacillus_gasseri_cluster, full_set$Gass, full_set$Lachnospiraceae_BVAB1, full_set$p_BVAB), by = list(full_set$race, full_set$reported_ga), mean)
colnames(count_table) <- c("race", "reported_ga", "Lactobacillus_iners", "p_Iners", "Crispatus", "p_Crisp", 
                           "Gardnerella", "p_Gard", "Gasseri", "p_Gass", "BVAB", "p_BVAB")
count_table <- count_table %>%
  arrange(race)
kable(count_table,  table.attr = "style = \"color: black;\"") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
```

```{r }
#Plot proportions over time, plot count over time
iners <- ggplot(count_table, aes(reported_ga, p_Iners)) + 
  geom_line(aes(group=race, color=race)) 
crisp <- ggplot(count_table, aes(reported_ga, p_Crisp)) + 
  geom_line(aes(group=race, color=race)) 
gard <- ggplot(count_table, aes(reported_ga, p_Gard)) + 
  geom_line(aes(group=race, color=race)) 
gass <- ggplot(count_table, aes(reported_ga, p_Gass)) + 
  geom_line(aes(group=race, color=race)) 
bvab <- ggplot(count_table, aes(reported_ga, p_BVAB)) + 
  geom_line(aes(group=race, color=race)) 
library(gridExtra)
ggarrange(iners, crisp, bvab, gard, gass, nrow = 3)
#Plot individuals for each race
#ggplot(full_set, aes(reported_ga, p_Iners)) + 
#  geom_line(aes(group=SUBJECT_ID, color=race)) + 
#  facet_wrap(~race, ncol=1)


#Look at those with the specific taxa as their vagitype
```


```{r}
prop_plot <- ggplot(full_set, aes(p_Iners)) + geom_histogram() + geom_vline(xintercept=mean(full_set$p_Iners), lwd=1, linetype=2, color="red") + geom_vline(xintercept=median(full_set$p_Iners), lwd=1, linetype=2, color="green")
#prop_plot
cprop_plot <- ggplot(full_set, aes(p_Crisp)) + geom_histogram() + geom_vline(xintercept=mean(full_set$p_Crisp), lwd=1, linetype=2, color="red") + geom_vline(xintercept=median(full_set$p_Crisp), lwd=1, linetype=2, color="green")
#iprop_plot

bprop_plot <- ggplot(full_set, aes(p_BVAB)) + geom_histogram() + geom_vline(xintercept=mean(full_set$p_BVAB), lwd=1, linetype=2, color="red") + geom_vline(xintercept=median(full_set$p_BVAB), lwd=1, linetype=2, color="green")
#pprop_plot

gprop_plot <- ggplot(full_set, aes(p_Gard)) + geom_histogram() + geom_vline(xintercept=mean(full_set$p_Gard), lwd=1, linetype=2, color="red") + geom_vline(xintercept=median(full_set$p_Gard), lwd=1, linetype=2, color="green")
#tprop_plot

gasprop_plot <- ggplot(full_set, aes(Gass)) + geom_histogram() + geom_vline(xintercept=mean(full_set$Gass), lwd=1, linetype=2, color="red") + geom_vline(xintercept=median(full_set$Gass), lwd=1, linetype=2, color="green")
#bprop_plot
#stratify by race
ggarrange(prop_plot, cprop_plot, bprop_plot, gprop_plot, gasprop_plot, labels = c("Iners","Crisp", "BVAB", "Gard", "Gass"), ncol = 3, nrow = 2)

```

```{r}
race_prop_plot <- ggplot(full_set, aes(p_Iners)) + geom_histogram(aes(group=race, fill=race)) + facet_wrap(~race) 

crace_prop_plot <- ggplot(full_set, aes(p_Crisp)) + geom_histogram(aes(group=race, fill=race)) + facet_wrap(~race) 

#stratify by race
brace_prop_plot <- ggplot(full_set, aes(p_BVAB)) + geom_histogram(aes(group=race, fill=race)) + facet_wrap(~race) 

grace_prop_plot <- ggplot(full_set, aes(p_Gard)) + geom_histogram(aes(group=race, fill=race)) + facet_wrap(~race)

gassrace_prop_plot <- ggplot(full_set, aes(Gass)) + geom_histogram(aes(group=race, fill=race)) + facet_wrap(~race)

ggarrange(race_prop_plot, crace_prop_plot, brace_prop_plot, grace_prop_plot, gassrace_prop_plot, nrow = 3)

```


```{r Count}
#Zero-Inflated Poisson Model
z <- glmmTMB(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div + (1|SUBJECT_ID), data = full_set, family = poisson, zi = ~ vaginal_pH + reported_ga + alpha_div)
summary(z)
hist(predict(z))

#summary(m1 <- zeroinfl(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div |SUBJECT_ID, data = full_set))
z <- glmmTMB(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div + (1|SUBJECT_ID), data = full_set, family = poisson, zi = ~ 0)
summary(z)
hist(predict(z))


#Zero-Inflated Negative Binomial Model
neg_bin<- glmmTMB(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div + offset(log(num_reads)) + (1|SUBJECT_ID), data = full_set, family = nbinom2, zi = ~ vaginal_pH + reported_ga + alpha_div)
summary(neg_bin)
predict(neg_bin)
neg_binone <- glmmTMB(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div + offset(log(num_reads)) + (1|SUBJECT_ID), data = full_set, family = nbinom2, zi = ~ 1)
summary(neg_binone)
hist(predict(neg_binone))
#Zero-Inflated Beta-Binomial Model
#kostic.y <- cbind(1, kostic.y=="Tumor")
# beta_bin<- glmmTMB(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div + race + (1|SUBJECT_ID), data = full_set, family=betabinomial(link = "logit"), zi = ~ vaginal_pH + reported_ga + alpha_div + race)


#Mixed Linear Regression Model
mixedL <- lmer(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div + race + (1|SUBJECT_ID), data = full_set)
summary(mixedL)
linpred <- predict(mixedL)
plot(full_set$Lactobacillus_iners[which(names(linpred) %in% rownames(full_set))], linpred)
#predicted
#x-axis people
#y-axis visits for that person
plot(full_set$Lactobacillus_iners[which(names(linpred) %in% rownames(full_set))], linpred)


## Beta bimonial zero inflated ##

## NBZIMM ##
f21 = glmm.zinb(Lactobacillus_iners ~ vaginal_pH + reported_ga + alpha_div , random = ~ 1|SUBJECT_ID, data = full_set)
summary(f21)
summary(f21)$tTable[4, 5]

```

```{r ProportionsData}
hist(full_set$p_Iners)
beta_bin<- glmmTMB(p_Iners ~ vaginal_pH + reported_ga + alpha_div + race + (1|SUBJECT_ID), data = full_set, family=betabinomial(link = "logit"), zi = ~ vaginal_pH + reported_ga + alpha_div + race)
mean(full_set$p_Iners)
var(full_set$p_Iners)

library(zoib)
#zoib
#zoib(p_Iners ~ vaginal_pH + reported_ga + alpha_div + race | 1|1, data = full_set, random = 1, EUID = full_set$SUBJECT_ID)
library(aod)
full_set$p_Iners[which(full_set$p_Iners == 1)] <- 0.99999
betaIners <- glmmTMB(p_Iners ~ vaginal_pH + reported_ga + alpha_div + race + (1|SUBJECT_ID), data = full_set, family=beta_family(link = "logit"), zi = ~ 1)
betapred <- predict(betaIners)
summary(betaIners)
#predicted
#x-axis people
#y-axis visits for that person
#plot(full_set$p_Iners[which(names(betapred) %in% rownames(full_set))], betapred)

#zoib(p_Iners ~ vaginal_pH + reported_ga + alpha_div + race | 1, data = full_set)


mixedL <- lmer(p_Iners ~ vaginal_pH + reported_ga + alpha_div + race + (1|SUBJECT_ID), data = full_set)

#par(mfrow = c(2,2))

coefplot2(mixedL)
plot(mixedL)
linpred <- predict(mixedL)

#predicted
#x-axis people
#y-axis visits for that person
plot(full_set$p_Iners[which(names(linpred) %in% rownames(full_set))], linpred)
```


```{r}
full_set$class_Iners <- as.factor(ifelse(full_set$p_Iners > mean(full_set$p_Iners), "High", "Low"))
full_set$class_Crisp <- as.factor(ifelse(full_set$p_Crisp > mean(full_set$p_Crisp), "High", "Low"))
full_set$class_Gass <- as.factor(ifelse(full_set$Gass > mean(full_set$Gass), "High", "Low"))
full_set$class_Gard <- as.factor(ifelse(full_set$p_Gard > mean(full_set$p_Gard), "High", "Low"))
full_set$class_BVAB <- as.factor(ifelse(full_set$p_BVAB > mean(full_set$p_BVAB), "High", "Low"))


#Check median
#add line to show where each point is
```


```{r}
#install.packages("ggpubr")
iners_plot <- ggplot(full_set, aes(class_Iners)) + geom_bar()
snea_plot <- ggplot(full_set, aes(class_Crisp)) + geom_bar() 
tm_plot <- ggplot(full_set, aes(class_Gass)) + geom_bar() 
prev_plot <- ggplot(full_set, aes(class_Gard)) + geom_bar() 
bvab_plot <- ggplot(full_set, aes(class_BVAB)) + geom_bar()

ggarrange(iners_plot, snea_plot, tm_plot, prev_plot, bvab_plot, labels = c("Iners", "Crisp", "Gass", "Gard", "BVAB1"), ncol = 3, nrow = 2)


```

```{r}
#Distribution of High and Low (do it across race)
irace_prop_plot <- ggplot(full_set, aes(class_Iners)) + geom_bar(aes(y= stat(prop),group=race, fill=race), position = "dodge2")+ ggtitle("Iners Dichotomized Histogram")
irace_prop_plot

#Distribution of High and Low (do it across race)
srace_prop_plot <- ggplot(full_set, aes(class_Crisp)) + geom_bar(aes(y= stat(prop), group=race, fill=race), position = "dodge2") + ggtitle("Crisp Dichotomized Histogram")


#Distribution of High and Low (do it across race)
prace_prop_plot <- ggplot(full_set, aes(class_Gass)) + geom_bar(aes(y= stat(prop), group=race, fill=race), position = "dodge2") +  ggtitle("Gass Dichotomized Histogram")


#Distribution of High and Low (do it across race)
trace_prop_plot <- ggplot(full_set, aes(class_Gard)) + geom_bar(aes(y= stat(prop), group=race, fill=race), position = "dodge2") + ggtitle("Gard Dichotomized Histogram")


#Distribution of High and Low (do it across race)
brace_prop_plot <- ggplot(full_set, aes(class_BVAB)) + geom_bar(aes(y= stat(prop),group=race, fill=race), position = "dodge2") + ggtitle("BVAB Dichotomized Histogram")


ggarrange(irace_prop_plot, srace_prop_plot, prace_prop_plot, trace_prop_plot, brace_prop_plot, nrow = 3)
#Use proportions instead of counts for better comparison, DONE
#position dodge, DONE
#Add proportion values to top of bars
#do facet wrap by taxa
```

```{r}
covs.taxa <- function(df, taxon, model, vars){
  tax_prop <- df[,taxon]/df[,"num_reads"]
   if(model == "fixed"){
    #covs <- vars
    model_data <- df[,vars]
    half <- paste(vars, collapse= "+")
  }
  else{
    #covs <- vars
    model_data <- df[,c(vars, "SUBJECT_ID", "num_reads")]
    half <- paste(paste(vars, collapse= "+"), " + (1|SUBJECT_ID)")
  }
  model_data <- cbind(tax_prop, model_data)
  no.na.data <- na.omit(model_data)
  form <- as.formula(paste("tax_prop ~ ", half))
  if(model == "fixed"){
    mod <- lm(form, data = no.na.data)
    step.back <- stepAIC(mod, direction = "backward")
    return(step.back)
    #return(mod)
  }
  else{
    mod <- lmer(form, data = no.na.data)
    return(mod)
    #return(mod.step)
  }
}


```


```{r }
taxa.glm <- function(df, taxon, type, model){
  tax_count <- df[,taxon]
  tax_prop <- df[,taxon]/df[,"num_reads"]
  class_tax <- as.factor(ifelse(tax_prop > mean(tax_prop), "High", "Low"))
  class_tax <- recode(class_tax, "High"= 1, "Low"= 0)
  if(model == "fixed"){
    covs <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "income", "bv_history", "phys", "antibiotics_current","age", "education", "prenatal_care_start", "infertility_treatment", "vdischarge", "vodor", "vitching", "douche", "vaginitis_history", "current_medications", "smoker_current", "alcohol_frequency_year", "diabetes", "no_false_labor", "no_high_bp", "no_vbleeding", "progesterone")
    model_data <- df[,covs]
    half <- paste(covs, collapse= "+")
  }
  else{
    covs <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "income", "bv_history", "phys", "antibiotics_current","age", "education", "prenatal_care_start", "infertility_treatment", "vdischarge", "vodor", "vitching", "douche", "vaginitis_history", "current_medications", "smoker_current", "alcohol_frequency_year", "diabetes", "no_false_labor", "no_high_bp", "no_vbleeding", "progesterone")
    model_data <- df[,c(covs, "SUBJECT_ID", "num_reads")]
    half <- paste(paste(covs, collapse= "+"), " + (1|SUBJECT_ID)")
  }
  if(type == "count"){
    model_data <- cbind(tax_count, model_data)
    no.na.data <- na.omit(model_data)
    form <- as.formula(paste("tax_count ~ ", half))
    if(model == "fixed"){
      mod <- glm.nb(form, data = no.na.data)
    }
    else{
      mod <- glmer.nb(form, data = no.na.data)
    }
  }
  else if(type == "prop"){
    model_data <- cbind(tax_prop, model_data)
    no.na.data <- na.omit(model_data)
    form <- as.formula(paste("tax_prop ~ ", half))
    if(model == "fixed"){
      mod <- lm(form, data = no.na.data)
      #return(mod)
    }
    else{
      mod <- lmer(form, data = no.na.data)
      return(mod)
      #return(mod.step)
    }
  }
  else{
    model_data <- cbind(class_tax, model_data)
    no.na.data <- na.omit(model_data)
    form <- as.formula(paste("class_tax ~ ", paste(covs, collapse= "+")))
    if(model == "fixed"){
      mod <- glm(form, data = no.na.data, family = binomial)
    }
    else{
      mod <- glmer(form, data = no.na.data, family = binomial, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))
    }
  }
  #step.model <- stepAIC(fixed_mod, direction = "both", trace = FALSE)
  step.back <- stepAIC(mod, direction = "backward", trace = FALSE)
  return(step.back)
  #TO ADD: Plot for each covariate the predicted distribution
  #Output table of common variables, extract p-value
}
```

```{r }
model_plot <- function(model){
  final_covs <- names(model$model)[-1]
  print(deparse(substitute(model)))
  print(as.formula(paste("class_tax ~ ", paste(final_covs, collapse= "+"))))
  #Plot AIC for model
  vars <- unlist(lapply(strsplit(as.character(model$anova$Step), '- ', fixed = TRUE), '[', 2))
  vars[1] <- "Intercept"
  AIC.res <- data.frame(Variable = vars, AIC = model$anova$AIC)
  AIC.res$Variable <- factor(AIC.res$Variable, levels = vars)
  #true variables
  #true_vars <- paste0("var", 1:10)
  #colour_vars <- ifelse(AIC.res$Variable %in% true_vars, 'red','black')
  plot <- ggplot(data=AIC.res, aes(x=Variable, y=AIC, group=1)) +
    geom_line(color = "red")+
    theme_bw()+
    theme(axis.text.x = element_text(angle = 60, hjust = 1))
  return(plot)
}
```

```{r }
pred_plot <- function(df, model){
  model_data <- df[,covs]
  model_data <- cbind(class_tax, model_data)
  no.na.data <- na.omit(model_data)
  final_covs <- names(model$model)[-1]
  pred_data <- no.na.data[,final_covs]
  return(predict(model, newdata=pred_data, type = "response"))
  
  
  
  # if(c("alpha_div","vagitype") %in% names(model$model)){
  #   plotting_dfm <- expand.grid(alpha_div = seq(0, 3.5, 0.01),
  #                          vagitype = c("Lactobacillus_crispatus_cluster", "Lactobacillus_iners", "Lachnospiraceae_BVAB1", "Gardnerella_vaginalis", "Lactobacillus_gasseri_cluster"))
  #   plotting_dfm$preds <- predict(model, newdata=plotting_dfm, type = "response")
  #   pl <- ggplot(plotting_dfm, aes(x=alpha_div, y =preds, color=as.factor(vagitype))) +
  #     geom_point( ) +
  #     ggtitle("Predicted High/Low by Alpha_Div and Vagitype")
  #   return(p1)
  # }
  # else{
  #   return ("No value")
  # }
}

```

```{r}
get_data <- function(taxon, df){
  tax_prop <- df[,taxon]/df[,"num_reads"]
  covs <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "income", "bv_history", "phys", "antibiotics_current","age", "education", "prenatal_care_start", "infertility_treatment", "vdischarge", "vodor", "vitching", "douche", "vaginitis_history", "current_medications", "smoker_current", "alcohol_frequency_year", "diabetes", "no_false_labor", "no_high_bp", "no_vbleeding", "progesterone")
  model_data <- df[,c(covs, "SUBJECT_ID", "num_reads")]
  model_data <- cbind(tax_prop, model_data)
  no.na.data <- na.omit(model_data)
  return(no.na.data)
}
```

```{r}
make_hists<- function(model, taxon, df, vars){
  hists <- data.frame(xx = c(predict(model, newdata = get_data(taxon, df)[, vars]), get_data(taxon, df)[, "tax_prop"]), yy = rep(c("pred", "actual"),each = length(get_data(taxon, df)[, "tax_prop"])))
  return(ggplot(hists, aes(x=xx, fill=yy)) + geom_histogram(alpha=0.2, position="identity"))
}

```

```{r}
agg_plot <- function(model, taxon, df, vars){
  ex <- data.frame(data = c(predict(model, newdata = get_data(taxon, df)[, vars]), get_data(taxon, df)[, "tax_prop"]), 
                   race = get_data(taxon, df)[, "race"], tri = get_data(taxon, df)[, "reported_ga"],
                   yy = rep(c("pred", "actual"),each = length(get_data(taxon, df)[, "tax_prop"])))
  agg_table <- aggregate(list(ex$data), by = list(ex$race, ex$tri, ex$yy), mean)
  colnames(agg_table) <- c("race", "tri", "type", "data")
  agg_plot <- ggplot(agg_table, aes(tri, data)) + 
geom_line(aes(group=interaction(race, type), color=race, linetype = type)) + 
    scale_x_discrete(labels=c("First Trimester" = "1st", "Second Trimester" = "2nd",
                              "Third Trimester" = "3rd")) + 
    ylab("Prop")
  return(agg_plot)
}

```

```{r}
getPerformace <- function(model, df){
  taxa <- colnames(t_otu)
  example <- c("Lactobacillus_iners", "Lactobacillus_crispatus_cluster", "Gardnerella_vaginalis", "Lachnospiraceae_BVAB1", "Lactobacillus_gasseri_cluster", "Sneathia_amnii", "Prevotella_cluster2", "TM7_OTU-H1")
  for (name in example){
    md <- covs.taxa
  }
  perf <- model_performance(model, metrics = "all", verbose = TRUE)
  return(perf)
  
}


```

```{r}
subsetFull <- function(df, taxalist){
  `%ni%` <- Negate(`%in%`)
  cols <- sapply(taxalist, function (x) any(df[,x]/df$num_reads > 0.05))
  df <- subset(df,select = names(df) %ni% names(which(cols == FALSE)))
  return(df)
}
  

```

```{r}
covs <- c("vaginal_pH", "alpha_div", "reported_ga", "race", "income", "bv_history", "phys", "antibiotics_current","age", "education", "prenatal_care_start", "infertility_treatment", "vdischarge", "vodor", "vitching", "douche", "vaginitis_history", "current_medications", "smoker_current", "alcohol_frequency_year", "diabetes", "no_false_labor", "no_high_bp", "no_vbleeding", "progesterone")
model_data <- full_set[,covs]
ggpairs(model_data, columns = 1:2, ggplot2::aes(colour=race)) #too many points, too many vagitypes as well so had to remove
#do top 5 vagitypes
aa <- full_set[full_set$race == 'african_american',]
histogram(aa$vaginal_pH)
```


```{r CompareModelType}
count_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "count", "fixed") #Does not converge
prop_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "prop", "fixed")
class_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "class", "fixed")
mcount_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "count", "mixed") #Does not converge
mprop_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "prop", "mixed") #failure to converge in 10000 evaluations
mod_Crisp <- taxa.glm(full_set, "Lactobacillus_crispatus_cluster", "class", "fixed")
mod_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "class", "fixed")
mod_BVAB <- taxa.glm(full_set, "Lachnospiraceae_BVAB1", "class", "fixed")
mod_Gard <- taxa.glm(full_set, "Gardnerella_vaginalis", "class", "fixed")
mod_Gass <- taxa.glm(full_set, "Lactobacillus_gasseri_cluster", "class", "fixed")


taxalist <- c("Lactobacillus_crispatus_cluster", "Lactobacillus_iners", "Lachnospiraceae_BVAB1", "Gardnerella_vaginalis", "Lactobacillus_gasseri_cluster")
var_df <- data.frame(matrix(ncol = 15, nrow = 15))
#colnames(var_df) <- taxalist
count <- 0
for(ind in c(1:length(taxalist))){
  mods <- taxa.glm(full_set, taxalist[ind], "prop", "mixed")
  no.na.data <- get_data(taxalist[ind], full_set)
  step.back <- lmerTest::step(mods)
  fix_vars <- c(rownames(step.back$fixed[which(step.back$fixed$Eliminated == 0),]), rownames(step.back$random[which(step.back$random$Eliminated == 0),]))
  for(i in c(1:length(fix_vars))){
    var_df[i,ind+count] <- fix_vars[i]
  }
  fixed_mods <- taxa.glm(full_set, taxalist[ind], "prop", "fixed")
  fixed_vars <- names(fixed_mods$model)[-1]
  for(i in c(1:length(fixed_vars))){
    var_df[i,ind+1+count] <- fixed_vars[i]
  }
  class_mods <- taxa.glm(full_set, taxalist[ind], "class", "fixed")
  class_vars <- names(class_mods$model)[-1]
  for(i in c(1:length(class_vars))){
    var_df[i,ind+2+count] <- class_vars[i]
  }
  count <- count + 2
}

colnames(var_df) <- c("Crisp_P_M", "Crisp_P_F", "Crisp_C_F", "Iners_P_M", "Iners_P_F","Iners_C_F", "BVAB1_P_M", "BVAB1_P_F","BVAB1_C_F","Gard_P_M", "Gard_P_F", "Gard_C_F","Gass_P_M","Gass_P_F", "Gass_C_F")
options(knitr.kable.NA = '')
kable(var_df, table.attr = "style = \"color: black;\"") %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  add_header_above(c("Crispatus" = 3, "Iners" = 3, "BVAB" = 3, "Gardnerella" = 3, "Gasseri" = 3))

```

```{r}
#Make table for the variables that are outputted
#need the data frame
#alpha div, vagitype, age, smoking, education, subject_id, vaginal_ph, race
#look at covariate estimates for each taxa model, consider correlations in model
#forward model selection, one variable addition at a time
#look at differences between taxa
#look for vagitypes in rare taxa
#performance with and without vagitype, compare using model comparison,ANOVA DONE
#overlay averages across each race across the 3 trimesters, output model metrics, try without and with vagitype: WROTE FUNCTION, APPLY TO ALL TAXA
#how much does vagitype add in terms of prediction, PLOTS DONE
#make summaries
#pca under both smoothed and unsmoother conditions
#prcomp on raw data, scale variables to same unit

vars <- c("vaginal_pH", "alpha_div", "race", "vagitype", "age", "education", "smoker_current")
mx_vars<- c("vaginal_pH", "alpha_div", "race", "vagitype", "age", "education", "smoker_current", "reported_ga","SUBJECT_ID")
mx_type <- c("vaginal_pH", "alpha_div", "race", "age", "education", "smoker_current", "reported_ga","SUBJECT_ID")
no_type <- c("vaginal_pH", "alpha_div", "race", "age", "education", "smoker_current")

#predict based on these models

taxalist <- c("Lactobacillus_iners", "Lactobacillus_crispatus_cluster", "Gardnerella_vaginalis", "Lachnospiraceae_BVAB1", "Lactobacillus_gasseri_cluster", "Sneathia_amnii", "Prevotella_cluster2", "TM7_OTU-H1")
tax_plots <- list()
tax_hists <- list()

#taxalist <- c("Lactobacillus_iners", "Lactobacillus_crispatus_cluster")
for (taxa in taxalist){
 mixed_full <- covs.taxa(full_set, taxa, "mixed", vars)
 mixed_notype <- covs.taxa(full_set, taxa, "mixed", no_type)
 print(taxa)
 print(anova(mixed_full, mixed_notype))
 #print(summary(mixed_notype))
 var = paste(taxa, "Full", sep = "_")
 var2 = paste(taxa, "NoType", sep = "_")
 tax_plots[[var]] <- agg_plot(mixed_full, taxa, full_set, mx_vars) + ggtitle(var)
 tax_plots[[var2]] <- agg_plot(mixed_notype, taxa, full_set, mx_type) + ggtitle(var2)
 tax_hists[[var]] <- make_hists(mixed_full, taxa, full_set, mx_vars) + ggtitle(var)
 tax_hists[[var2]] <- make_hists(mixed_notype, taxa, full_set, mx_type) + ggtitle(var2)
}
new_list = c("Lactobacillus_iners", "Lactobacillus_crispatus_cluster", "Gardnerella_vaginalis", "Lachnospiraceae_BVAB1", "Lactobacillus_gasseri_cluster")
perf <- data.frame()
predFrame <- data.frame()
see <- subsetFull(full_set, names(t_otu))
updated <- t_otu[,(names(t_otu) %in% names(see))]

#comb <- data.frame()
for (taxa in names(updated)){
  mixed_full <- covs.taxa(see, taxa, "mixed", vars)
  if (taxa %in% new_list){
    orig <- paste(taxa, "Orig", sep = "_")
    predicted <- paste(taxa, "Pred", sep = "_")
    pre_dat <- getData(mixed_full)
    pred <- predict(mixed_full)
    comb[1:length(pred),c(orig, predicted)] <- cbind(pre_dat[,c("tax_prop", "SUBJECT_ID")], pred)
    # comb <- comb %>%
    #   rename(!!orig := tax_prop, !!predicted := pred)
  }
  var = paste(taxa, "Full", sep = "_")
  predFrame[1:length(predict(mixed_full)),taxa] <- predict(mixed_full)
  perf[taxa,names(model_performance(mixed_full, metrics = "all", verbose = TRUE))] <- model_performance(mixed_full, metrics = "all", verbose = TRUE)
}
predFrame[predFrame < 0] <- 0
predFrame[predFrame > 1] <- 1
comb[comb < 0] <- 0
comb[comb > 1] <- 1
comb <- comb[ , c(2, 1, 3:ncol(comb))]
no_na <- na.omit(full_set[, vars])
pred_Full <- cbind(predFrame, no_na)
#Get the actual from the initial model
#Add in subject_id
#Truncate, DONE
```

```{r}
perf$rankRMSE <- rank(perf$RMSE)
perf$rankR2Cond <- rank(-perf$R2_conditional)
perf$Name <- rownames(perf)
kable(perf,  table.attr = "style = \"color: black;\"") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))
#make boxplot for the metrics and look at outliers, use rmse
#see rank of metrics for specific taxa of interest
#add column for quantiles for the specific taxa of interest

rmse <- ggplot(perf, aes(x="RMSE", y=RMSE)) + 
  geom_boxplot() +
  geom_point(data=subset(perf, rownames(perf) %in% new_list), 
    aes(x="RMSE", y=RMSE), 
    color="red", size=5) +
  geom_text_repel(data=subset(perf, rownames(perf) %in% new_list), aes(label=Name))
rmse

r2_cond <- ggplot(perf, aes(x="R2_Cond", y=R2_conditional)) + 
  geom_boxplot() +
  geom_point(data=subset(perf, rownames(perf) %in% new_list), 
    aes(x="R2_Cond", y=R2_conditional), 
    color="red", size=5) +
  geom_text_repel(data=subset(perf, rownames(perf) %in% new_list), aes(label=Name))
r2_cond
```

```{r PredActual}
grouped <- aggregate(. ~ SUBJECT_ID, comb, mean)
grouped$rows <- as.numeric(rownames(grouped))

sorted <- comb %>%
  group_by(SUBJECT_ID) %>%
  filter(n() > 7)
sorted <- sorted %>%
  group_by(SUBJECT_ID) %>%
  mutate(id = row_number())
sorted <- ungroup(sorted)


ins = ggplot() + 
  geom_line(data = sorted, aes(x=id, y=Lactobacillus_iners_Orig,group=as.factor(SUBJECT_ID)), color = "blue") +
  geom_line(data = sorted, aes(x=id, y=Lactobacillus_iners_Pred,group=as.factor(SUBJECT_ID)), color = "red") +
  xlab('Number of Visits') +
  ylab('Prop_Iners') +
  ggtitle("Lactobacillus iners over time")
ins <- ggplotly(ins)
ins

crp = ggplot() + 
  geom_line(data = sorted, aes(x=id, y=Lactobacillus_crispatus_cluster_Orig,group=SUBJECT_ID), color = "blue") +
  geom_line(data = sorted, aes(x=id, y=Lactobacillus_crispatus_cluster_Pred,group=SUBJECT_ID), color = "red") +
  xlab('Number of Visits') +
  ylab('Prop_Crisp') +
  ggtitle("Lactobacillus crispatus over time")
crp <- ggplotly(crp)
crp

grd = ggplot() + 
  geom_line(data = sorted, aes(x=id, y=Gardnerella_vaginalis_Orig,group=SUBJECT_ID), color = "blue") +
  geom_line(data = sorted, aes(x=id, y=Gardnerella_vaginalis_Pred,group=SUBJECT_ID), color = "red") +
  xlab('Number of Visits') +
  ylab('Prop_Gard') +
  ggtitle("Gardnerella vaginalis over time")
grd <- ggplotly(grd)
grd

bvb = ggplot() + 
  geom_line(data = sorted, aes(x=id, y=Lachnospiraceae_BVAB1_Orig,group=SUBJECT_ID), color = "blue") +
  geom_line(data = sorted, aes(x=id, y=Lachnospiraceae_BVAB1_Pred,group=SUBJECT_ID), color = "red") +
  xlab('Number of Visits') +
  ylab('Prop_BVAB1') +
  ggtitle("BVAB1 over time")
bvb <- ggplotly(bvb)
bvb

gas = ggplot() + 
  geom_line(data = sorted, aes(x=id, y=Lactobacillus_gasseri_cluster_Orig,group=SUBJECT_ID), color = "blue") +
  geom_line(data = sorted, aes(x=id, y=Lactobacillus_gasseri_cluster_Pred,group=SUBJECT_ID), color = "red") +
  xlab('Number of Visits') +
  ylab('Prop_Gass') +
  ggtitle("Lactobacillus gasseri over time") +
  guides(fill=guide_legend(title="Orig/Pred"))
gas <- ggplotly(gas)
gas



#How to best effectively plot all taxa for predicted vs actual without having too many graphs
#sindex
# ggplot(aes(x = hp, y = mpg)) +
#   geom_smooth(method = "lm", se = FALSE, color = "lightgrey") +
#   geom_segment(aes(xend = hp, yend = predicted), alpha = .2) +
# 
#   # > Color adjustments made here...
#   geom_point(aes(color = residuals)) +  # Color mapped here
#   scale_color_gradient2(low = "blue", mid = "white", high = "red") +  # Colors to use here
#   guides(color = FALSE) +
#   # <
# 
#   geom_point(aes(y = predicted), shape = 1) +
#   theme_bw()

#Do high, medium, low for residuals
#Legend
#Add each subject id, color by id, line type by predicted/acutal
```

```{r TrimesterPlots}
marrangeGrob(tax_plots, nrow = 2, ncol = 2)
```

```{r Histograms}
marrangeGrob(tax_hists, nrow = 2, ncol = 2)
```

```{r}
#add predicted vs actual plot, y = x
#put table for prediction summary/statistics, See if should add more, 
#drop all taxa that have proportion of 0.05 or below, DONE
#which(apply(t_otu, 2, sum) == 0)
pca_orig <- prcomp(updated, scale = TRUE)
coords_orig <- pca_orig$x[,1:2]
#pca_other <- prcomp(otu, scale = TRUE)
pca_pred <- prcomp(predFrame, scale = TRUE)
coords_pred <- pca_pred$x[,1:2]
rot_pre <- pca_pred$rotation[,1:2]
#pca_predT <- prcomp(t(predFrame), scale = TRUE)
#print(pca_orig)
#scriplot, DONE
#summary(pca_orig)
ggarrange(autoplot(pca_orig, data = see, colour = "race"),autoplot(pca_pred, data = pred_Full, colour = "race"),
          labels = c("Orig", "Pred"))
screeplot(pca_orig)
screeplot(pca_pred)

fviz_pca_var(pca_orig,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
fviz_pca_var(pca_pred,
             col.var = "contrib", # Color by contributions to the PC
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
#plot pca for variables and variable loadings, extract subject scores, get coordinates of each point
#How to limit number of variable loadings to top 10?
#Overlay on first loading
#Plot x y for rotational
```


```{r}
autoplot(pca_pred, data = pred_Full, colour = "race")
screeplot(pca_pred)
```
```{r}
iners_f_hist <- make_hists(iners_fixed, "Lactobacillus_iners", full_set, vars) + ggtitle("Iners Fixed Plot")
iners_m_hist <- make_hists(iners_mixed, "Lactobacillus_iners", full_set, mx_vars) + ggtitle("Iners Mixed Plot")
ggarrange(iners_f_hist, iners_m_hist)

```

```{r}
crisp_f_hist <- make_hists(crisp_fixed, "Lactobacillus_crispatus_cluster", full_set, vars) + ggtitle("Crisp Fixed Plot")
crisp_m_hist <- make_hists(crisp_mixed, "Lactobacillus_crispatus_cluster", full_set, mx_vars) + ggtitle("Crisp Mixed Plot")
ggarrange(crisp_f_hist, crisp_m_hist)

#clean age, set blanks to NA, clean values, make 18-28 reference group
# do individual plots
# quantify prediction success
# get model summaries
# perform on more taxa
#education, high_school_ged is baseline, put in order of ascending degree

```

```{r }
#predictions <- pred_plot(full_set, mod_Iners)
#lapply(models, model_plot)

mod_Crisp <- taxa.glm(full_set, "Lactobacillus_crispatus_cluster", "class", "fixed")
mod_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "class", "fixed")
mod_BVAB <- taxa.glm(full_set, "Lachnospiraceae_BVAB1", "class", "fixed")
mod_Gard <- taxa.glm(full_set, "Gardnerella_vaginalis", "class", "fixed")
mod_Gass <- taxa.glm(full_set, "Lactobacillus_gasseri_cluster", "class", "fixed")

prop_Crisp <- taxa.glm(full_set, "Lactobacillus_crispatus_cluster", "prop", "fixed")
prop_Iners <- taxa.glm(full_set, "Lactobacillus_iners", "prop", "fixed")
prop_BVAB <- taxa.glm(full_set, "Lachnospiraceae_BVAB1", "prop", "fixed")
prop_Gard <- taxa.glm(full_set, "Gardnerella_vaginalis", "prop", "fixed")
prop_Gass <- taxa.glm(full_set, "Lactobacillus_gasseri_cluster", "prop", "fixed")

ggarrange(model_plot(mod_Crisp), model_plot(prop_Crisp),labels = c("Class Crisp", "Prop Crisp"))
ggarrange(model_plot(mod_Iners), model_plot(prop_Iners),labels = c("Class Iners", "Prop Iners"))
ggarrange(model_plot(mod_BVAB), model_plot(prop_BVAB),labels = c("Class BVAB", "Prop BVAB"))
ggarrange(model_plot(mod_Crisp), model_plot(prop_Iners),labels = c("Class Gard", "Prop Gard"))
ggarrange(model_plot(mod_Gass), model_plot(prop_Gass),labels = c("Class Gass", "Prop Gass"))
model_plot(mod_Crisp) + ggtitle("Class Crispatus")
model_plot(mod_Iners) + ggtitle("Class Iners")
model_plot(mod_BVAB) + ggtitle("Class BVAB")
model_plot(mod_Gard) + ggtitle("Class Gardnerella")
model_plot(mod_Gass) + ggtitle("Class Gasseri")

#alpha_div and vagitype show up in almost every model vaginal_pH in most of them
#correlations between data
#longitudinal plots when stratifying by covariates
#count and proportion plots
#Look at model pre and post aic
#ggaly and regular correlation matrix
#Look at distribution of NA's in covariate (pre-filtering) and see if it affects model by removing it
```


```{r }
mixed_Iners <- taxa.glm(full_set, "Lactobacillus_crispatus_cluster", "mean", "mixed")
#Some linear combination of the parameters perfectly separates failure from successes, I assume it's vagitype
#Doesn't run still

```


```{r}
na.test <-  function (x) {
  w <- sapply(x, function(x)all(is.na(x)))
  if (any(w)) {
    stop(paste("All NA in columns", paste(which(w), collapse=", ")))
  }
}
#Recode High to 1 and Low to 0
full_set[["class_Iners"]] <- recode(full_set[["class_Iners"]], "High"= 1, "Low"= 0)
full_set$class_Iners <- as.factor(full_set$class_Iners)


covs <- c("class_Iners", "vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "income", "bv", "phys", "antibiotics_current","SUBJECT_ID")
model_data <- full_set[,covs]
no.na.data <- na.omit(model_data)

reduced_mod <- glmer(class_Iners ~ alpha_div + vagitype + (1|SUBJECT_ID), data = no.na.data, family = binomial, control=glmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5))) #Unable to evaluate scaled gradient, model fails to converge
step.model <- stepAIC(log_mod, direction = "both", 
                      trace = FALSE)
#install.packages("ResourceSelection")
library(ResourceSelection)

fixed_mod <- glm(class_Iners ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + phys + bv + antibiotics_current, data = no.na.data, family = binomial) 
step.model <- stepAIC(fixed_mod, direction = "both", 
                      trace = FALSE)
step.back <- stepAIC(fixed_mod, direction = "backward")
hoslem.test(no.na.data$class_Iners, fitted(fixed_mod))
hoslem.test(no.na.data$class_Iners, fitted(step.model))
# model becomes class_Iners ~ alpha_div + vagitype
predict(fixed_mod, type = "response")
histogram(predict(fixed_mod, type = "response"))
plot(predict(fixed_mod, type = "response"), full_set$class_Iners)



plotting_dfm <- expand.grid(alpha_div = seq(0, 3.5, 0.01),
                           vagitype = c("Lactobacillus_crispatus_cluster", "Lactobacillus_iners", "Lachnospiraceae_BVAB1", "Gardnerella_vaginalis", "Lactobacillus_gasseri_cluster"))
plotting_dfm$preds <- predict(step.model, newdata=plotting_dfm, type = "response")
pl <- ggplot(plotting_dfm, aes(x=alpha_div, y =preds, color=as.factor(vagitype)))
pl + 
  geom_point( ) +
  ggtitle("Predicted High/Low by Alpha_Div and Vagitype")

#Look at alpha div and vagitype over trimesters and see how it changes 
# plot those who change
#Table of amt that change vs not change
```

```{r }
reduced_mod <- glmer(class_Crisp ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + (1|SUBJECT_ID), data = full_set, family = binomial) #Does not converge
reduced_mod <- glmer(class_Gass ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + (1|SUBJECT_ID), data = full_set, family = binomial) #Does not converge
reduced_mod <- glmer(class_Gard ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + (1|SUBJECT_ID), data = full_set, family = binomial) #Does not converge
reduced_mod <- glmer(class_BVAB ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + (1|SUBJECT_ID), data = full_set, family = binomial) #Does not converge
```

```{r}
library(caret)

#Split Data 80:20
training.samps <- full_set$class_Iners %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- full_set[training.samps,]
test.data <- full_set[-training.samps,]
#Linear discriminant analysis
#install.packages("mda")
library(mda)
covs_test <- as.data.frame(test.data[,cov])
full_set$vagitype <- as.factor(full_set$vagitype)
full_set$SUBJECT_ID <- as.factor(full_set$SUBJECT_ID)
mda_model <- mda(class_Iners ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + SUBJECT_ID, data = full_set)
#summary(mda_model)
mda_model$percent.explained
mda_model$confusion
covs <- covs[which(names(pred) %in% rownames(full_set)),]
#mda_pred <- predict(mda_model,test.data)


# SVM
library(e1071)
rownames(full_set) <- rownames(meta)
cov <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "income", "SUBJECT_ID")
covs <- as.data.frame(full_set[,cov])
svm_model <- svm(class_Iners ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + income + SUBJECT_ID, data = full_set, type = "C")
pred <- predict(svm_model, covs)
table(pred, full_set$class_Iners[which(names(pred) %in% rownames(full_set))])
#Random Forest
#try randomforest with formula and see if random var works
#install.packages("randomForest")
#library(randomForest)
#full_set$vagitype <- as.character(full_set$vagitype)
#full_set$SUBJECT_ID <- as.character(full_set$SUBJECT_ID)
#forest_model <- randomForest(class_Iners ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = full_set, na.action=na.omit, importance = TRUE)

```

```{r Snea}

#Split Data 80:20
training.samps <- full_set$class_Snea %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- full_set[training.samps,]
test.data <- full_set[-training.samps,]
#Linear discriminant analysis
#install.packages("mda")
library(mda)
covs_test <- as.data.frame(test.data[,cov])
full_set$vagitype <- as.factor(full_set$vagitype)
full_set$SUBJECT_ID <- as.factor(full_set$SUBJECT_ID)
mda_model <- mda(class_Snea ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = train.data)
#summary(mda_model)
mda_model$percent.explained
mda_model$confusion
covs <- covs[which(names(pred) %in% rownames(full_set)),]
#mda_pred <- predict(mda_model,test.data)


# SVM
library(e1071)
rownames(full_set) <- rownames(meta)
cov <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "SUBJECT_ID")
covs <- as.data.frame(full_set[,cov])
svm_model <- svm(class_Snea ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = full_set, type = "C")
pred <- predict(svm_model, covs)
table(pred, full_set$class_Snea[which(names(pred) %in% rownames(full_set))])
```


```{r Prev}

#Split Data 80:20
training.samps <- full_set$class_Prev %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- full_set[training.samps,]
test.data <- full_set[-training.samps,]
#Linear discriminant analysis
#install.packages("mda")
library(mda)
covs_test <- as.data.frame(test.data[,cov])
full_set$vagitype <- as.factor(full_set$vagitype)
full_set$SUBJECT_ID <- as.factor(full_set$SUBJECT_ID)
mda_model <- mda(class_Prev ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = train.data)
#summary(mda_model)
mda_model$percent.explained
covs <- covs[which(names(pred) %in% rownames(full_set)),]
mda_model$confusion

#mda_pred <- predict(mda_model,test.data)


# SVM
library(e1071)
rownames(full_set) <- rownames(meta)
cov <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "SUBJECT_ID")
covs <- as.data.frame(full_set[,cov])
svm_model <- svm(class_Prev ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = full_set, type = "C")
pred <- predict(svm_model, covs)
table(pred, full_set$class_Prev[which(names(pred) %in% rownames(full_set))])
```

```{r TM7}

#Split Data 80:20
training.samps <- full_set$class_TM %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- full_set[training.samps,]
test.data <- full_set[-training.samps,]
#Linear discriminant analysis
#install.packages("mda")
library(mda)
covs_test <- as.data.frame(test.data[,cov])
full_set$vagitype <- as.factor(full_set$vagitype)
full_set$SUBJECT_ID <- as.factor(full_set$SUBJECT_ID)
mda_model <- mda(class_TM ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = train.data)
#summary(mda_model)
mda_model$percent.explained
covs <- covs[which(names(pred) %in% rownames(full_set)),]
mda_model$confusion
#mda_pred <- predict(mda_model,test.data)


# SVM
library(e1071)
rownames(full_set) <- rownames(meta)
cov <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "SUBJECT_ID")
covs <- as.data.frame(full_set[,cov])
svm_model <- svm(class_TM ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = full_set, type = "C")
pred <- predict(svm_model, covs)
table(pred, full_set$class_TM[which(names(pred) %in% rownames(full_set))])
```

```{r BVAB}

#Split Data 80:20
training.samps <- full_set$class_BVAB %>%
  createDataPartition(p = 0.8, list = FALSE)
train.data <- full_set[training.samps,]
test.data <- full_set[-training.samps,]
#Linear discriminant analysis
#install.packages("mda")
library(mda)
covs_test <- as.data.frame(test.data[,cov])
full_set$vagitype <- as.factor(full_set$vagitype)
full_set$SUBJECT_ID <- as.factor(full_set$SUBJECT_ID)
mda_model <- mda(class_BVAB ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = train.data)
#summary(mda_model)
mda_model$percent.explained
covs <- covs[which(names(pred) %in% rownames(full_set)),]
mda_model$confusion
#mda_pred <- predict(mda_model,test.data)


# SVM
library(e1071)
rownames(full_set) <- rownames(meta)
cov <- c("vaginal_pH", "reported_ga", "alpha_div", "race", "vagitype", "SUBJECT_ID")
covs <- as.data.frame(full_set[,cov])
svm_model <- svm(class_BVAB ~ vaginal_pH + reported_ga + alpha_div + race + vagitype + SUBJECT_ID, data = full_set, type = "C")
pred <- predict(svm_model, covs)
table(pred, full_set$class_BVAB[which(names(pred) %in% rownames(full_set))])
```

